/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f8f82576-ee08-44a0-b578-f7273e890711",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_PXfBwK4dc",
    "aws_user_pools_web_client_id": "3hb3d0grjgifbnoadpod4sa677",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://wffxad6oefht7hrrltsslsd7jy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-tztaoz5egzgp7g4einanpdsriq",
    "aws_user_files_s3_bucket": "amplifyapp55183af808674dd095a405a8eb5c99fa152606-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
